name: fraud-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.24.3
  - pandas=1.5.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - jupyter=1.0.0
  - notebook=6.5.4
  - pip:
    - -r requirements.txt